name: docker

on:
  push:
    branches:
      - "main"
      - "feature/**"
  pull_request:
    branches:
      - "main"

jobs:
  docker:
    permissions:
      contents: read
    runs-on: "ubuntu-latest"
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v7
      - name: Run CI tests for Docker
        run: make ci-test-docker
